# Generated by Django 4.2.3 on 2023-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_alumno_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_examen',
            field=models.DateField(null=True),
        ),
    ]
