# Generated by Django 4.2.3 on 2023-07-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alumno_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='descripcion',
            field=models.TextField(help_text='Ingrese una breve descripción del alumno', max_length=1000, null=True),
        ),
    ]
