# Generated by Django 4.2.3 on 2023-07-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_alumno_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='descripcion',
        ),
    ]
