# Generated by Django 4.2.3 on 2023-07-17 04:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alumno_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text='Ingrese una breve descripción del alumno', max_length=1000, null=True),
        ),
    ]
