# Generated by Django 4.2.3 on 2023-07-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_alumno_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='imagen_alumno',
            field=models.ImageField(blank=True, null=True, upload_to='img_alumno'),
        ),
    ]
